services:
  backend:
    build: .
    container_name: event_planner_backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: event_planner_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
